variables:
     GIT_SUBMODULE_STRATEGY: recursive

image: ruby:2.6-alpine3.13
before_script:
  - ruby -v
  - apk update
  - apk add build-base bison git curl valgrind
  - which ruby

test:
  tags:
    - ruby
  script:
    - make
    - tail gcov.log -n 1
  coverage: '/^Lines executed *: *(\d+\.\d+%) of/'
