variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: ruby:alpine
before_script:
  - ruby -v
  - apk update
  - apk add bash build-base bison git curl valgrind gcovr
  - which ruby

test:
  variables:
    RED_TEXT: "\e[10m"
    GREEN_TEXT: "\e[32m"
    LRED_TEXT: "\e[91m"
    NORMAL_TEXT: "\e[0m"
  tags:
    - cpp
  script:
    - LEAKCHECK=1 make
    - make coverage
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: coverage.xml

pages:
  tags:
    - cpp
  stage: deploy
  script:
    - make coverage
    - mkdir .public
    - cp coverage.html .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
