version: 2.0
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run:
          name: Install
          command: 'sudo apt-get update && sudo apt-get install -y bison'
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build