version: 2.0
jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run:
          name: Install
          command: 'apt-get update && apt-get install -y bison && gem install coveralls specific_install && gem specific_install https://github.com/davidsiaw/coveralls-gcov'
      - run:
          name: Build and Test
          command: 'make'
      - run:
          name: Submit coverage report
          command: 'coveralls-gcov send --repo-token $COVERALLS_TOKEN --root `pwd` --exclude mruby --exclude-pattern "tests/"'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build